services:
  esphome:
    image: ghcr.io/esphome/esphome:2025.12.7
    container_name: esphome
    restart: unless-stopped
    volumes:
      - /home/kacper/Dev/docker-volumes/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    environment:
      - USERNAME=test
      - PASSWORD=ChangeMe
